plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    mainClass = 'com.voxcom.vox.App'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.firebase:firebase-admin:9.2.0'
    implementation 'ai.picovoice:porcupine-java:4.0.0'
    implementation 'org.json:json:20240303'
    implementation platform('com.google.cloud:libraries-bom:26.43.0')
    implementation 'net.sf.sociaal:freetts:1.2.2'
}